# Regressão Linear

## Nem sempre quando tivermos montando uma rede neural teremos a mesma estrutura. Dependendo da complexidade/natureza do nosso problemas, podemos ter diferentes arquiteturas para resolver dado problema

### Tentando ser generalista, o que geralmente vai se repetir (no caso da regressão linear):

* **Camada de Saída:** Tem 1 único neurônio (units=1) e NENHUMA função de ativação (ou ativação linear). Isso permite que a rede preveja qualquer valor real contínuo ($-\infty$ a $+\infty$, como preços, notas, temperaturas).

* **Função de Perda (Loss):** Sempre usamos métricas de erro numérico como MSE (Mean Squared Error) ou MAE (Mean Absolute Error).

* **Métrica de Avaliação:** mae ou mse (em vez de accuracy, que só serve para classificação).

### Tentando ser generalista, o que geralmente vai mudar (no caso da regressão linear):

* Quantidade de neurônios nas camadas ocultas (ex: 16, 32, 64).
  
* Quantidade de camadas intermediárias (1 ou 2 são suficientes para a maioria dos problemas tabulares simples).

* Funções de ativação intermediárias (quase sempre relu).

<br>

### Algumas Diferenças entre os problemas Regressão vs. Classificação (tensorflow/Keras):

<br>

| **Componente** | **Problema de Regressão** | **Classificação Binária (0 ou 1)** | **Classificação Multiclasse (ex: 10 dígitos)** |
| --- | --- | --- | --- |
| **Última Camada (`Dense`)** | `Dense(1)` | `Dense(1, activation='sigmoid')` | `Dense(num_classes, activation='softmax')` |
| **Função de Perda (`loss`)** | `'mse'` ou `'mae'` | `'binary_crossentropy'` | `'sparse_categorical_crossentropy'` |
| **Métricas (`metrics`)** | `['mae', 'mse']` | `['accuracy']` | `['accuracy']` |

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787958427.784647  253515 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1787958427.818086  253515 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787958428.721553  253515 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

<br>

### Base de Dados

In [2]:
# Carregando o dataset de preços de imóveis
dados = fetch_california_housing(as_frame=True)
X = dados.data[['MedInc', 'HouseAge', 'AveRooms']]  # Renda média, idade do imóvel, média de quartos
y = dados.target  # Preço da casa em centenas de milhares de dólares

In [4]:
# display(X)

# display(y)

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

<br>

### Separação dos dados de Treino e Teste

In [5]:
# Divisão Treino e Teste (lembram Scikit-Learn)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<br>
<br>

### IMPORTANTE PARA REDES NEURAIS: Normalização dos dados!
### Redes neurais aprendem muito melhor se os dados estiverem na mesma escala.

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

<br>
<br>

### Aqui vamos definir qual a estrura da rede para resolver o problema em questão.

In [7]:
# input_shape=[3] porque temos, como vimos acima, 3 colunas de entrada
modelo_regressao = Sequential([
    # Camada Oculta 1: 16 neurônios aprendem relações não-lineares
    Dense(16, activation='relu', input_shape=[3]),
    
    # Camada Oculta 2: 8 neurônios combinam os padrões aprendidos
    Dense(8, activation='relu'),
    
    # CAMADA DE SAÍDA DE REGRESSÃO (pensando no tipo de problema que temos na regressão): 
    # 1 neurônio, sem ativação (produz o valor contínuo do preço)
    Dense(1)
])

W0000 00:00:1787958607.089921  253515 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

<br>

### Compilação do Modelo

In [8]:
modelo_regressao.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss='mean_squared_error',  # Penaliza erros grandes (MSE)
    metrics=['mae']             # Erro médio absoluto em $100k pra ficar mais fácil interpretação
)

<br>

### Treinamento
Treinando a Rede Neural de Regressão

In [17]:
historico = modelo_regressao.fit(
    X_train_scaled, y_train,
    validation_split=0.2,       # Separa 20% do treino para validação a cada época
    epochs=100,
    batch_size=64,
    verbose=1
)

Epoch 1/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - loss: 0.5362 - mae: 0.5312 - val_loss: 0.5456 - val_mae: 0.5326
Epoch 2/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 0.5365 - mae: 0.5310 - val_loss: 0.5416 - val_mae: 0.5276
Epoch 3/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.5373 - mae: 0.5319 - val_loss: 0.5418 - val_mae: 0.5301
Epoch 4/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 0.5373 - mae: 0.5320 - val_loss: 0.5424 - val_mae: 0.5278
Epoch 5/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 0.5380 - mae: 0.5339 - val_loss: 0.5464 - val_mae: 0.5375
Epoch 6/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 0.5386 - mae: 0.5325 - val_loss: 0.5440 - val_mae: 0.5328
Epoch 7/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 0.5385 - mae: 0.5328 - val_loss: 0.5470 - val_mae: 0.5428
Epoch 8/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 0.5401 - mae: 0.5333 - val_loss: 0.5452 - val_mae: 0.5416
Epoch 9/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 0.5372 - mae: 0.5327 - val_loss: 0.5417 - val_mae: 0.5310
Epoch 10/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - loss: 0.5417 - mae: 0.5357 - val_loss: 0.5416 - val_mae: 0.5379
Epoch 11/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step - loss: 0.5393 - mae: 0.5328 - val_loss: 0.5408 - val_mae: 0.5405
Epoch 12/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - loss: 0.5402 - mae: 0.5350 - val_loss: 0.5475 - val_mae: 0.5285
Epoch 13/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5404 - mae: 0.5347 - val_loss: 0.5567 - val_mae: 0.5411
Epoch 14/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - loss: 0.5390 - mae: 0.5330 - val_loss: 0.5481 - val_mae: 0.5332
Epoch 15/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 0.5412 - mae: 0.5343 - val_loss: 0.5721 - val_mae: 0.5644
Epoch 16/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 0.5378 - mae: 0.5326 - val_loss: 0.5494 - val_mae: 0.5393
Epoch 17/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - loss: 0.5437 - mae: 0.5357 - val_loss: 0.5446 - val_mae: 0.5356
Epoch 18/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 0.5399 - mae: 0.5347 - val_loss: 0.5791 - val_mae: 0.5696
Epoch 19/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 0.5407 - mae: 0.5351 - val_loss: 0.5426 - val_mae: 0.5369
Epoch 20/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step - loss: 0.5397 - mae: 0.5325 - val_loss: 0.5419 - val_mae: 0.5369
Epoch 21/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 0.5392 - mae: 0.5344 - val_loss: 0.5445 - val_mae: 0.5295
Epoch 22/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - loss: 0.5377 - mae: 0.5330 - val_loss: 0.5433 - val_mae: 0.5283
Epoch 23/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 0.5393 - mae: 0.5338 - val_loss: 0.5433 - val_mae: 0.5250
Epoch 24/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - loss: 0.5403 - mae: 0.5336 - val_loss: 0.5508 - val_mae: 0.5471
Epoch 25/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - loss: 0.5392 - mae: 0.5341 - val_loss: 0.5650 - val_mae: 0.5513
Epoch 26/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 0.5432 - mae: 0.5357 - val_loss: 0.5445 - val_mae: 0.5368
Epoch 27/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 0.5409 - mae: 0.5349 - val_loss: 0.5559 - val_mae: 0.5298
Epoch 28/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - loss: 0.5381 - mae: 0.5322 - val_loss: 0.5528 - val_mae: 0.5527
Epoch 29/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - loss: 0.5393 - mae: 0.5333 - val_loss: 0.5442 - val_mae: 0.5337
Epoch 30/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 0.5385 - mae: 0.5336 - val_loss: 0.5452 - val_mae: 0.5277
Epoch 31/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 0.5383 - mae: 0.5321 - val_loss: 0.5504 - val_mae: 0.5281
Epoch 32/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step - loss: 0.5415 - mae: 0.5345 - val_loss: 0.5404 - val_mae: 0.5308
Epoch 33/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - loss: 0.5381 - mae: 0.5326 - val_loss: 0.5473 - val_mae: 0.5289
Epoch 34/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 0.5382 - mae: 0.5326 - val_loss: 0.5434 - val_mae: 0.5350
Epoch 35/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - loss: 0.5386 - mae: 0.5339 - val_loss: 0.5450 - val_mae: 0.5272
Epoch 36/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - loss: 0.5407 - mae: 0.5337 - val_loss: 0.5454 - val_mae: 0.5349
Epoch 37/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 0.5404 - mae: 0.5352 - val_loss: 0.5475 - val_mae: 0.5359
Epoch 38/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step - loss: 0.5403 - mae: 0.5335 - val_loss: 0.5486 - val_mae: 0.5290
Epoch 39/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 0.5365 - mae: 0.5318 - val_loss: 0.5467 - val_mae: 0.5299
Epoch 40/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 0.5400 - mae: 0.5343 - val_loss: 0.5443 - val_mae: 0.5335
Epoch 41/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - loss: 0.5389 - mae: 0.5342 - val_loss: 0.5449 - val_mae: 0.5364
Epoch 42/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 0.5384 - mae: 0.5321 - val_loss: 0.5572 - val_mae: 0.5564
Epoch 43/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - loss: 0.5419 - mae: 0.5343 - val_loss: 0.5482 - val_mae: 0.5358
Epoch 44/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - loss: 0.5382 - mae: 0.5330 - val_loss: 0.5457 - val_mae: 0.5360
Epoch 45/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - loss: 0.5371 - mae: 0.5315 - val_loss: 0.5443 - val_mae: 0.5440
Epoch 46/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - loss: 0.5417 - mae: 0.5358 - val_loss: 0.5448 - val_mae: 0.5315
Epoch 47/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - loss: 0.5400 - mae: 0.5343 - val_loss: 0.5500 - val_mae: 0.5301
Epoch 48/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - loss: 0.5355 - mae: 0.5315 - val_loss: 0.5425 - val_mae: 0.5349
Epoch 49/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 0.5381 - mae: 0.5326 - val_loss: 0.5466 - val_mae: 0.5239
Epoch 50/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step - loss: 0.5374 - mae: 0.5330 - val_loss: 0.5510 - val_mae: 0.5247
Epoch 51/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - loss: 0.5381 - mae: 0.5326 - val_loss: 0.5414 - val_mae: 0.5285
Epoch 52/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 0.5369 - mae: 0.5320 - val_loss: 0.5501 - val_mae: 0.5380
Epoch 53/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 0.5405 - mae: 0.5342 - val_loss: 0.5566 - val_mae: 0.5251
Epoch 54/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 0.5447 - mae: 0.5363 - val_loss: 0.5405 - val_mae: 0.5307
Epoch 55/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - loss: 0.5377 - mae: 0.5328 - val_loss: 0.5466 - val_mae: 0.5255
Epoch 56/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5369 - mae: 0.5322 - val_loss: 0.5402 - val_mae: 0.5296
Epoch 57/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - loss: 0.5370 - mae: 0.5319 - val_loss: 0.5496 - val_mae: 0.5356
Epoch 58/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5409 - mae: 0.5343 - val_loss: 0.5406 - val_mae: 0.5310
Epoch 59/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 0.5371 - mae: 0.5325 - val_loss: 0.5439 - val_mae: 0.5335
Epoch 60/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 0.5372 - mae: 0.5326 - val_loss: 0.5442 - val_mae: 0.5366
Epoch 61/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 0.5370 - mae: 0.5323 - val_loss: 0.5556 - val_mae: 0.5424
Epoch 62/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.5359 - mae: 0.5322 - val_loss: 0.5441 - val_mae: 0.5326
Epoch 63/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - loss: 0.5369 - mae: 0.5327 - val_loss: 0.5427 - val_mae: 0.5309
Epoch 64/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 0.5351 - mae: 0.5311 - val_loss: 0.5419 - val_mae: 0.5426
Epoch 65/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 0.5319 - mae: 0.5313 - val_loss: 0.5470 - val_mae: 0.5354
Epoch 66/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 0.5343 - mae: 0.5313 - val_loss: 0.5443 - val_mae: 0.5249
Epoch 67/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - loss: 0.5326 - mae: 0.5306 - val_loss: 0.5426 - val_mae: 0.5332
Epoch 68/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5326 - mae: 0.5309 - val_loss: 0.5442 - val_mae: 0.5368
Epoch 69/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 0.5317 - mae: 0.5309 - val_loss: 0.5423 - val_mae: 0.5360
Epoch 70/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step - loss: 0.5352 - mae: 0.5324 - val_loss: 0.5435 - val_mae: 0.5256
Epoch 71/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - loss: 0.5322 - mae: 0.5310 - val_loss: 0.5445 - val_mae: 0.5342
Epoch 72/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 0.5356 - mae: 0.5331 - val_loss: 0.5434 - val_mae: 0.5407
Epoch 73/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 0.5324 - mae: 0.5310 - val_loss: 0.5621 - val_mae: 0.5578
Epoch 74/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - loss: 0.5344 - mae: 0.5325 - val_loss: 0.5424 - val_mae: 0.5327
Epoch 75/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 0.5363 - mae: 0.5337 - val_loss: 0.5435 - val_mae: 0.5302
Epoch 76/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - loss: 0.5347 - mae: 0.5328 - val_loss: 0.5527 - val_mae: 0.5266
Epoch 77/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 0.5324 - mae: 0.5300 - val_loss: 0.5434 - val_mae: 0.5345
Epoch 78/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - loss: 0.5328 - mae: 0.5314 - val_loss: 0.5436 - val_mae: 0.5369
Epoch 79/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 0.5302 - mae: 0.5292 - val_loss: 0.5510 - val_mae: 0.5463
Epoch 80/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 0.5336 - mae: 0.5317 - val_loss: 0.5427 - val_mae: 0.5326
Epoch 81/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - loss: 0.5308 - mae: 0.5294 - val_loss: 0.5426 - val_mae: 0.5383
Epoch 82/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - loss: 0.5331 - mae: 0.5312 - val_loss: 0.5587 - val_mae: 0.5535
Epoch 83/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - loss: 0.5311 - mae: 0.5304 - val_loss: 0.5413 - val_mae: 0.5307
Epoch 84/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - loss: 0.5306 - mae: 0.5292 - val_loss: 0.5717 - val_mae: 0.5399
Epoch 85/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 0.5326 - mae: 0.5312 - val_loss: 0.5499 - val_mae: 0.5451
Epoch 86/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - loss: 0.5325 - mae: 0.5313 - val_loss: 0.5486 - val_mae: 0.5389
Epoch 87/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - loss: 0.5333 - mae: 0.5313 - val_loss: 0.5421 - val_mae: 0.5262
Epoch 88/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 0.5329 - mae: 0.5311 - val_loss: 0.5535 - val_mae: 0.5498
Epoch 89/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 0.5332 - mae: 0.5329 - val_loss: 0.5447 - val_mae: 0.5319
Epoch 90/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - loss: 0.5306 - mae: 0.5294 - val_loss: 0.5479 - val_mae: 0.5450
Epoch 91/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 0.5319 - mae: 0.5311 - val_loss: 0.5595 - val_mae: 0.5493
Epoch 92/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - loss: 0.5317 - mae: 0.5305 - val_loss: 0.5401 - val_mae: 0.5379
Epoch 93/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - loss: 0.5321 - mae: 0.5306 - val_loss: 0.5419 - val_mae: 0.5388
Epoch 94/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 0.5328 - mae: 0.5313 - val_loss: 0.5393 - val_mae: 0.5312
Epoch 95/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 0.5312 - mae: 0.5296 - val_loss: 0.5405 - val_mae: 0.5305
Epoch 96/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 0.5304 - mae: 0.5305 - val_loss: 0.5471 - val_mae: 0.5471
Epoch 97/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5330 - mae: 0.5305 - val_loss: 0.5444 - val_mae: 0.5338
Epoch 98/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 0.5328 - mae: 0.5310 - val_loss: 0.5408 - val_mae: 0.5319
Epoch 99/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - loss: 0.5347 - mae: 0.5321 - val_loss: 0.6143 - val_mae: 0.6042
Epoch 100/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 0.5336 - mae: 0.5329 - val_loss: 0.5427 - val_mae: 0.5256

<br>
<br>

### Podemos avaliar e tentar fazer previsões

In [10]:
# Fazendo predições no conjunto de teste que a rede nunca viu
predicoes = modelo_regressao.predict(X_test_scaled).flatten()

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step

In [11]:
# Podemos calcular algumas métricas de desempenho
mae = mean_absolute_error(y_test, predicoes)
r2 = r2_score(y_test, predicoes)

In [12]:
print("\nResultados no conj. de teste")
print(f"Erro Médio Absoluto (MAE): ${mae * 100_000:,.2f}")
print(f"R² Score: {r2:.3f}")

Resultados no conj. de teste
Erro Médio Absoluto (MAE): $53,578.02
R² Score: 0.569

In [13]:
# Vamos fazer uma tabela para poder comparar y e y_chapeu para alguns valores
tabela_comparacao = pd.DataFrame({
    'Valor Real ($100k)': y_test.iloc[:10].values,
    'Valor Previsto ($100k)': np.round(predicoes[:10], 2)
})

In [14]:
print("\nAmostra de Previsões:")
tabela_comparacao

Amostra de Previsões:

   Valor Real ($100k)  Valor Previsto ($100k)
0             0.47700                    1.07
1             0.45800                    1.17
2             5.00001                    2.86
3             2.18600                    2.56
4             2.78000                    1.78
5             1.58700                    2.06
6             1.98200                    2.56
7             1.57500                    2.00
8             3.40000                    2.38
9             4.46600                    4.59

In [15]:
tabela_comparacao['erro'] = np.abs(tabela_comparacao['Valor Real ($100k)'] - tabela_comparacao['Valor Previsto ($100k)'])

In [16]:
tabela_comparacao

   Valor Real ($100k)  Valor Previsto ($100k)     erro
0             0.47700                    1.07  0.59300
1             0.45800                    1.17  0.71200
2             5.00001                    2.86  2.14001
3             2.18600                    2.56  0.37400
4             2.78000                    1.78  1.00000
5             1.58700                    2.06  0.47300
6             1.98200                    2.56  0.57800
7             1.57500                    2.00  0.42500
8             3.40000                    2.38  1.02000
9             4.46600                    4.59  0.12400